import "@/app/globals.css"
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Cart',
  description: 'Generated by create next app',
}

export default function PageLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (

    <div className={`${inter.className} h-screen bg-gray-300`}>{children}</div>
   
  )
}
